name: stream_cipher
description: A library to encrypt and decrypt ByteLists and ByteLists Streams
  initially comes with DioHttpClientAdapter
repository: https://github.com/HemendCo/stream_cipher
version: 1.1.4

environment:
  sdk: ">=2.17.5 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  shelf:
  shelf_router:
  shelf_plus:
  logger:
dependencies:
  dio: ^4.0.6
  pointycastle: ^3.6.0

false_secrets:
  - test/stream_cipher_test.dart
